version: "3.9"

services:
  text-classification:
    image: oblivion208/asr:2.3.0-gpu
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ipc: "host"
    ports:
      - 6006:6006
    working_dir: /app
    volumes:
      - ./:/app
